version: '2'
services:
  backend:
    build: .
    image: typist_backend
    container_name: typist_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_URI: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: dev
      DB_PASSWORD: dev123
      S3_ACCESS_KEY: access_key
      S3_SECRET_KEY: secret_key
      S3_BUCKET: bucket
      S3_REGION: region
      S3_DEFAULT_USER_IMAGE: default

  frontend:
    build: frontend/front
    image: typist_frontend
    container_name: typist_frontend
    ports:
      - "4000:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API: http://backend:8080/api/

  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123