services:
  backend:
    build: ./backend/
    image: typist-backend
    container_name: typist_backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      PORT: 8080
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: root
      MONGODB_DATABASE: typist

  # frontend:
  #   build: ./frontend/
  #   image: typist-frontend
  #   container_name: typist_frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

  mongodb:
    image: mongo
    container_name: mongodb-typist
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
