
spring:
  datasource:
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
server:
  port: ${PORT:8080}

aws:
  s3:
    access-key-id: ${S3_ACCESS_KEY}
    secret-access-key: ${S3_SECRET_KEY}
    bucket-name: ${S3_BUCKET}
    region: ${S3_REGION}
    default-user-image: ${S3_DEFAULT_USER_IMAGE}