spring:
  datasource:
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
server:
  port: ${PORT:8080}

security:
  jwt:
    secret: jwt.super.secret.key
    token-expiration-time-min: 10080

words:
  path: words
  min-count-per-request: 1
  max-count-per-request: 1000
