spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
      authentication-database: ${MONGODB_AUTHENTICATION_DB:admin}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

server:
  port: ${PORT:8080}

security:
  jwt:
    secret: jwt.super.secret.key
    token-expiration-time-min: 10080

words:
  path: words
  min-count-per-request: 1
  max-count-per-request: 1000

image-store:
  upload-path: images
  allowed-extensions-regex: jpg|jpeg|png|bmp