spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
      authentication-database: ${MONGODB_AUTHENTICATION_DB:admin}
      auto-index-creation: true
  
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

  mail:
    host: ${MAIL_SERVER}
    port: ${MAIL_SERVER_PORT}
    username: ${MAIL_SERVER_USERNAME}
    password: ${MAIL_SERVER_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true

email:
  from: no-reply@typist
  confirmation-url: ${CONFIRMATION_URL:localhost:8080/api/auth/confirm/}
  redirect-url: ${EMAIL_CONFIRMATION_REDIRECT:http://localhost:3000/}

server:
  port: ${PORT:8080}

security:
  jwt:
    secret: jwt.super.secret.key
    token-expiration-time-min: 10080

words:
  path: words
  min-count-per-request: 1
  max-count-per-request: 1000

image-store:
  upload-path: images
  allowed-extensions-regex: jpg|jpeg|png|bmp

logging:
  level:
    com.example.typist: DEBUG